# Generated by Django 3.1.6 on 2021-05-08 13:32

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidcheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCity',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('_pin', models.IntegerField(db_column='pin', default=0)),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='check',
            old_name='other_symptoms',
            new_name='_other_symptoms',
        ),
        migrations.AddField(
            model_name='check',
            name='date',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='date_published'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='check',
            name='phone',
            field=models.IntegerField(
                default=1234567890, verbose_name='phone_number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='_other_symptoms',
            field=models.IntegerField(db_column='other_symptoms', default=0),
        ),
        migrations.AlterField(
            model_name='check',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
