# Generated by Django 3.1.6 on 2021-05-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidcheck', '0002_auto_20210508_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='phone',
        ),
    ]
