# Generated by Django 3.1.6 on 2021-05-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidcheck', '0003_remove_check_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='phone',
            field=models.IntegerField(default=1234567890, verbose_name='phone_number'),
            preserve_default=False,
        ),
    ]
